# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from settings_to_make_qr import SETTINGS_QR, TRANSLATE_COLORS
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(40, 250, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.version = QtWidgets.QLabel(Dialog)
        self.version.setGeometry(QtCore.QRect(10, 10, 51, 21))
        self.version.setObjectName("version")
        self.version_spinBox = QtWidgets.QSpinBox(Dialog)
        self.version_spinBox.setGeometry(QtCore.QRect(210, 10, 71, 21))
        self.version_spinBox.setObjectName("version_spinBox")
        self.border_spinBox = QtWidgets.QSpinBox(Dialog)
        self.border_spinBox.setGeometry(QtCore.QRect(210, 110, 71, 21))
        self.border_spinBox.setObjectName("border_spinBox")
        self.box_size_spinBox = QtWidgets.QSpinBox(Dialog)
        self.box_size_spinBox.setGeometry(QtCore.QRect(210, 60, 71, 21))
        self.box_size_spinBox.setObjectName("box_size_spinBox")
        self.fill_color_comboBox = QtWidgets.QComboBox(Dialog)
        self.fill_color_comboBox.setGeometry(QtCore.QRect(210, 160, 71, 21))
        self.fill_color_comboBox.setObjectName("fill_color_comboBox")
        self.fill_color_comboBox.addItem("")
        self.fill_color_comboBox.addItem("")
        self.fill_color_comboBox.addItem("")
        self.fill_color_comboBox.addItem("")
        self.fill_color_comboBox.addItem("")
        self.fill_color_comboBox.addItem("")
        self.fill_color_comboBox.addItem("")
        self.fill_color_comboBox.addItem("")
        self.fill_color_comboBox.addItem("")
        self.border = QtWidgets.QLabel(Dialog)
        self.border.setGeometry(QtCore.QRect(10, 110, 81, 21))
        self.border.setObjectName("border")
        self.back_color = QtWidgets.QLabel(Dialog)
        self.back_color.setGeometry(QtCore.QRect(10, 210, 61, 21))
        self.back_color.setObjectName("back_color")
        self.fill_color = QtWidgets.QLabel(Dialog)
        self.fill_color.setGeometry(QtCore.QRect(10, 160, 61, 21))
        self.fill_color.setObjectName("fill_color")
        self.box_size = QtWidgets.QLabel(Dialog)
        self.box_size.setGeometry(QtCore.QRect(10, 60, 81, 21))
        self.box_size.setObjectName("box_size")
        self.back_color_comboBox_2 = QtWidgets.QComboBox(Dialog)
        self.back_color_comboBox_2.setGeometry(QtCore.QRect(210, 210, 71, 21))
        self.back_color_comboBox_2.setObjectName("back_color_comboBox_2")
        self.back_color_comboBox_2.addItem("")
        self.back_color_comboBox_2.addItem("")
        self.back_color_comboBox_2.addItem("")
        self.back_color_comboBox_2.addItem("")
        self.back_color_comboBox_2.addItem("")
        self.back_color_comboBox_2.addItem("")
        self.back_color_comboBox_2.addItem("")
        self.back_color_comboBox_2.addItem("")
        self.back_color_comboBox_2.addItem("")

        self.version_spinBox.setRange(1, 40)
        self.box_size_spinBox.setRange(10, 20)
        self.border_spinBox.setRange(1, 10)
        self.fill_color_comboBox.activated[str].connect(self.fill_color_set)
        self.back_color_comboBox_2.activated[str].connect(self.back_color_set)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)  # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def fill_color_set(self, text):
        global SETTINGS_QR
        SETTINGS_QR["fill_color"] = TRANSLATE_COLORS[text]

    def back_color_set(self, text):
        global SETTINGS_QR
        SETTINGS_QR["back_color"] = TRANSLATE_COLORS[text]

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Настройки"))
        self.version.setText(_translate("Dialog", "Версия:"))
        self.fill_color_comboBox.setItemText(0, _translate("Dialog", "Чёрный"))
        self.fill_color_comboBox.setItemText(1, _translate("Dialog", "Белый"))
        self.fill_color_comboBox.setItemText(2, _translate("Dialog", "Красный"))
        self.fill_color_comboBox.setItemText(3, _translate("Dialog", "Оранжевый"))
        self.fill_color_comboBox.setItemText(4, _translate("Dialog", "Жёлтый"))
        self.fill_color_comboBox.setItemText(5, _translate("Dialog", "Зелёный"))
        self.fill_color_comboBox.setItemText(6, _translate("Dialog", "Голубой"))
        self.fill_color_comboBox.setItemText(7, _translate("Dialog", "Синий"))
        self.fill_color_comboBox.setItemText(8, _translate("Dialog", "Фиолетовый"))
        self.border.setText(_translate("Dialog", "Толщина рамки:"))
        self.back_color.setText(_translate("Dialog", "Цвет фона:"))
        self.fill_color.setText(_translate("Dialog", "Цвет кода:"))
        self.box_size.setText(_translate("Dialog", "Размер клетки:"))
        self.back_color_comboBox_2.setItemText(0, _translate("Dialog", "Белый"))
        self.back_color_comboBox_2.setItemText(1, _translate("Dialog", "Чёрный"))
        self.back_color_comboBox_2.setItemText(2, _translate("Dialog", "Красный"))
        self.back_color_comboBox_2.setItemText(3, _translate("Dialog", "Оранжевый"))
        self.back_color_comboBox_2.setItemText(4, _translate("Dialog", "Жёлтый"))
        self.back_color_comboBox_2.setItemText(5, _translate("Dialog", "Зелёный"))
        self.back_color_comboBox_2.setItemText(6, _translate("Dialog", "Голубой"))
        self.back_color_comboBox_2.setItemText(7, _translate("Dialog", "Синий"))
        self.back_color_comboBox_2.setItemText(8, _translate("Dialog", "Фиолетовый"))
